spring.application.name=elternsprechtag
vaadin.launch-browser=true

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/elternsprechtag
spring.datasource.username=myuser
spring.datasource.password=mysecret

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Organizer Login Credentials
elternsprechtag.security.organizer.username=user
elternsprechtag.security.organizer.password={bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG